from app.services.auth import AuthenticationError, authenticate_user
from app.services.bootstrap import ensure_bootstrap_user
from app.services.catalog import build_location_asset_catalog, find_or_create_asset
from app.services.demo import ensure_demo_data, is_demo_user_email, list_demo_users
from app.services.passwords import hash_password, verify_password
from app.services.workflow import (
    ASSIGNEE_REQUIRED_STATUSES,
    ASSIGNMENT_ROLES,
    COORDINATION_ROLES,
    DEFAULT_STAGE_BY_STATUS,
    EVENT_TYPE_BY_STATUS,
    OPERATIONS_ROLES,
    REASON_REQUIRED_STATUSES,
    ROLE_GROUPS_BY_TARGET,
    STATUS_EVENT_MESSAGES,
    TRIAGE_ROLES,
    ALLOWED_STATUS_CHANGES,
    EventSpec,
    append_event,
    apply_status_change,
    assignee_label,
    assignee_scope,
    default_owner_scope,
    default_responsibility_owner,
    default_stage_for_actor,
    fallback_status_for_unassigned,
    job_has_assignee,
    require_status_permission,
    role_label,
    status_label,
    touch_job,
    user_role_label,
    validate_assignee_required,
)

__all__ = [
    "ALLOWED_STATUS_CHANGES",
    "AuthenticationError",
    "ASSIGNEE_REQUIRED_STATUSES",
    "ASSIGNMENT_ROLES",
    "COORDINATION_ROLES",
    "DEFAULT_STAGE_BY_STATUS",
    "EVENT_TYPE_BY_STATUS",
    "EventSpec",
    "OPERATIONS_ROLES",
    "REASON_REQUIRED_STATUSES",
    "ROLE_GROUPS_BY_TARGET",
    "STATUS_EVENT_MESSAGES",
    "TRIAGE_ROLES",
    "authenticate_user",
    "append_event",
    "apply_status_change",
    "assignee_label",
    "assignee_scope",
    "build_location_asset_catalog",
    "default_owner_scope",
    "default_responsibility_owner",
    "default_stage_for_actor",
    "ensure_demo_data",
    "ensure_bootstrap_user",
    "fallback_status_for_unassigned",
    "find_or_create_asset",
    "hash_password",
    "is_demo_user_email",
    "job_has_assignee",
    "list_demo_users",
    "require_status_permission",
    "role_label",
    "status_label",
    "touch_job",
    "user_role_label",
    "validate_assignee_required",
    "verify_password",
]
